version: '3'
services:

  php-apache:
    image: webdevops/php-apache:8.3
    container_name: sample1
    ports:
      - 8901:80
    volumes:
      - ./:/var/www
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html

  mysql:
    image: mysql:8.4
    container_name: sample184
    volumes:
      - mysql84:/var/lib/mysql84
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sample1-phpMyAdmin
    links:
      - mysql
    ports:
      - 8889:80
    environment:
      PMA_HOSTS: mysql
      PMA_PORT: 3307

volumes:
  mysql84:
